package com.aivashin.model.graph

import kotlinx.serialization.Serializable

/**
 * State object representing the execution context of the Database Optimizer Graph pipeline.
 *
 * This data class is passed sequentially through each node in the optimization graph state machine,
 * accumulating metadata, extracted schemas, generated SQL, validation results, and diagnostic errors.
 *
 * @property sessionId Unique identifier for the user session or request context, used for logging and tracking.
 * @property userQuery The original SQL query or optimization problem provided by the user.
 * @property tableNamesInQuery Database table names identified by [queryAnalyzerNode] as relevant to the optimization request.
 * @property isWebSearchNeeded Flag determined by [queryAnalyzerNode] indicating whether external web research (e.g. Postgres best practices) is needed.
 * @property extractedSchema Database schema information extracted from live PostgreSQL tables by [contextAggregatorNode].
 * @property webResearchData Web search findings gathered by [contextAggregatorNode] via external tools (e.g. Tavily).
 * @property generatedRawSql The candidate optimized SQL script generated by [solutionArchitectNode].
 * @property explanation Human-readable explanation produced by [solutionArchitectNode] describing the optimizations made.
 * @property isSafe Security flag evaluated by [securityGuardNode]; `false` indicates potential SQL injection or destructive operations (e.g. DROP/DELETE).
 * @property validationErrors Audit errors or risks flagged by [selfReflectionNode] (e.g. missing indexes, locking risks); triggers the self-correction loop if non-empty.
 * @property systemErrors System-level failure messages (e.g. LLM API errors or tool execution failures) collected during node execution.
 * @property iterationCount Counter tracking how many times the self-correction loop ([solutionArchitectNode] <-> [selfReflectionNode]) has executed.
 */
@Serializable
data class OptimizerState(
    val sessionId: String,
    val userQuery: String,
    val tableNamesInQuery: List<String> = emptyList(),
    val isWebSearchNeeded: Boolean = false,
    val extractedSchema: String = "",
    val webResearchData: String = "",
    val generatedRawSql: String = "",
    val explanation: String = "",
    val isSafe: Boolean = true,
    val validationErrors: List<String> = emptyList(),
    val systemErrors: List<String> = emptyList(),
    val iterationCount: Int = 0
)