version: '3.8'

services:
  postgres:
    image: postgres:18.4
    container_name: ktor_koog_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktor-koog-playground
    ports:
      - "5432:5432"
    volumes:
      - ktor_koog_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ktor_koog_postgres_data: