ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.aivashin.configuration.AgentModuleKt.agentModule

database:
  url: jdbc:postgresql://localhost:5432/ktor-koog-playground
  user: postgres
  password: postgres

agents:
  api:
    geminiApiKey: $GEMINI_API_KEY
