[versions]
kotlin = "2.4.10"
coroutines = "1.11.0"
logback = "1.5.34"
kotlin-logging = "8.0.4"
koog = "1.1.1"
koog-beta = "1.1.1-beta"
postgresql = "42.7.10"
hikari = "6.2.1"
postgresql-r2dbc = "1.1.2.RELEASE"
r2dbc-pool = "1.0.2.RELEASE"
h2 = "2.3.232"
r2dbc-h2 = "1.0.0.RELEASE"
opentelemetry = "1.61.0"
mockk = "1.14.11"
kotest = "6.2.2"
testcontainers = "2.0.5"

[libraries]
# Logs
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }

# Coroutines
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }

# Koog
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }
koog-agents-additions = { module = "ai.koog:koog-agents-additions", version.ref = "koog-beta" }
koog-agents-features-sql = { module = "ai.koog:agents-features-sql", version.ref = "koog" }
koog-agents-features-chat-memory-jdbc = { module = "ai.koog:agents-features-chat-memory-sql", version.ref = "koog" }
koog-agents-features-chat-history-jdbc = { module = "ai.koog:agents-features-chat-history-jdbc", version.ref = "koog" }
koog-agents-test = { module = "ai.koog:agents-test", version.ref = "koog" }

# DB
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
postgresql-r2dbc = { module = "org.postgresql:r2dbc-postgresql", version.ref = "postgresql-r2dbc" }
r2dbc-pool = { module = "io.r2dbc:r2dbc-pool", version.ref = "r2dbc-pool" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
r2dbc-h2 = { module = "io.r2dbc:r2dbc-h2", version.ref = "r2dbc-h2" }

# Telemetry
opentelemetry-exporter-logging = { module = "io.opentelemetry:opentelemetry-exporter-logging", version.ref = "opentelemetry" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp", version.ref = "opentelemetry" }

# Testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
